routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::post('/report', 'SendReportController@store')->name('report');
    Route::resource('states.license', StateLicensesController::class, [
        'only' => ['index', 'store']
    ]);
});

Route::get('/home', 'HomeController@index')->name('home');

app/License.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class License extends Model
{
    protected $dates = ['expire_at'];
    protected $fillable = [
        'number', 'expire_at'
    ];

    public function state()
    {
        return $this->belongsTo(State::class);
    }
}

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    protected $fillable = ['name'];

    public function license()
    {
        return $this->hasOne(License::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\State;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $states = State::with('license')->get();
        return view('home', compact('states'));
    }
}

app/Http/Controllers/SendReportController.php
<?php

namespace App\Http\Controllers;

use App\License;
use App\Mail\GenerateReport;
use App\State;
use PDF;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class SendReportController extends Controller
{
    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email'
        ]);

        $licenses = License::get();
        $states = State::with('license')->get();

        $pdf = PDF::loadView('pdf.license', compact('states'))
                    ->save(storage_path().'/licenses/licenses.pdf');

        Mail::to($request->email)
            ->send(new GenerateReport($licenses));;

        return back();
    }
}

app/Http/Controllers/StateLicensesController.php
<?php

namespace App\Http\Controllers;

use App\State;
use Carbon\Carbon;
use Illuminate\Http\Request;

class StateLicensesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($state)
    {
        $state = State::with('license')->find($state);
        return view('licenses.edit', compact('state'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $state)
    {
        $this->validate($request, [
            'number' => 'required|unique:licenses,number,' . $state . ',state_id',
            'expire_at' => 'required|date',
        ]);

        $state = State::with('license')->find($state);

        $date = Carbon::parse($request->expire_at);
        if ($state->license) {
            $state->license()->update([
                'number' => $request->number,
                'expire_at' => $date,
            ]);
        } else {
            $state->license()->create([
                'number' => $request->number,
                'expire_at' => $date,
            ]);
        }
        

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h1>Licenses</h1>
        </div>
        <div class="col-sm-6"><br>
            <form action="{{ route('report')}}" class="form-inline pull-right" method="POST">
                {{ csrf_field() }}
                <input type="email" name="email" required class="form-control">
                <button class="btn btn-primary">Send Report</button>
            </form>
        </div>
        <div class="col-sm-12">
            <div class="panel panel-default">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>State</th>
                            <th>License Number</th>
                            <th>Expiration Date</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($states as $state)
                            @if($state->license)
                                <tr>
                                    <td><a href="{{ route('states.license.index', $state->id) }}">{{ $state->name }}</a></td>
                                    <td>{{ $state->license->number }}</td>
                                    <td>{{ $state->license->expire_at->format("m/d/Y") }}</td>
                                    <td>
                                        @if($state->license->expire_at->lt(now()))
                                            <span class="text-danger"><i class="fa fa-times-circle fa-fw"></i> License Invalid</span>
                                        @else
                                            <span class="text-success"><i class="fa fa-check-circle fa-fw"></i> License Valid</span>
                                        @endif
                                    </td>
                                </tr>
                            @else
                                <tr>
                                    <td><a href="{{ route('states.license.index', $state->id) }}">{{ $state->name }}</a></td>
                                    <td><span class="text-danger">No License Found</span></td>
                                    <td><span class="text-danger">No License Found</span></td>
                                    <td><span class="text-danger"><i class="fa fa-times-circle fa-fw"></i> No License Found</span></td>
                                </tr>
                            @endif
                        @empty
                            <tr>
                                <td colspan="4" align="center">No State Found</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/licenses/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="panel panel-default">
                <div class="panel-body">
                    @if(count($errors))
                        @foreach($errors->all() as $e)
                            <div class="alert alert-danger">
                                <p>{{ $e }}</p>
                            </div>
                        @endforeach
                    @endif
                    <form action="{{ route('states.license.store', $state->id) }}" method="POST">
                        <div class="form-group">
                            <label for="state">State</label>
                            <p>{{ $state->name }}</p>
                        </div>
                        <div class="form-group">
                            <label for="number">License Number</label>
                            <input type="text" required name="number" class="form-control"
                                value="{{ old('number', $state->license ? $state->license->number : '') }}">
                        </div>
                        <div class="form-group">
                            <label for="number">License Expiration</label>
                            <input type="date" required name="expire_at" class="form-control"
                                value="{{ old('expire_at', $state->license ? $state->license->expire_at->format('Y-m-d') : now()->addMonth()->format("Y-m-d")) }}">
                        </div>
                        {{ csrf_field() }}
                        <button class="btn btn-primary">Save</button>
                        <a href="/home" class="btn btn-default">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pdf/license.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="panel panel-default">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>State</th>
                        <th>License Number</th>
                        <th>Expiration Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($states as $state)
                        @if($state->license)
                            <tr>
                                <td>{{ $state->name }}</td>
                                <td>{{ $state->license->number }}</td>
                                <td>{{ $state->license->expire_at->format("m/d/Y") }}</td>
                                <td>
                                    @if($state->license->expire_at->lt(now()))
                                        <span class="text-danger"><i class="fa fa-times-circle fa-fw"></i> License Invalid</span>
                                    @else
                                        <span class="text-success"><i class="fa fa-check-circle fa-fw"></i> License Valid</span>
                                    @endif
                                </td>
                            </tr>
                        @else
                            <tr>
                                <td>{{ $state->name }}</td>
                                <td><span class="text-danger">No License Found</span></td>
                                <td><span class="text-danger">No License Found</span></td>
                                <td><span class="text-danger"><i class="fa fa-times-circle fa-fw"></i> No License Found</span></td>
                            </tr>
                        @endif
                    @empty
                        <tr>
                            <td colspan="4" align="center">No State Found</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>